name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          template.tex
          template_wo_maketitle.tex
        compiler: latexmk
        args: -file-line-error -halt-on-error -interaction=nonstopmode
    - name: upload result files
      uses: actions/upload-artifact@v1
      with:
        name: pdf_${{ github.sha }}
        path: |
          template.pdf
          template_wo_maketitle.pdf
