name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          template.tex
          template_wo_maketitle.tex
        compiler: latexmk
        args: -file-line-error -halt-on-error
    - name : copy pdf files
      run: |
        mkdir pdfs
        echo "Generated pdfs"
        ls *.pdf
        echo "-------------"
        cp *.pdf ./pdfs
    - name: upload result files
      uses: actions/upload-artifact@v2
      with:
        name: pdfs_${{ github.sha }}
        path: pdfs
